apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stage2-rbac-editor
  namespace: ronaldo-stage2
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-stage2-rbac-editor
  namespace: ronaldo-stage2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stage2-rbac-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: CPaaS-stage-ronaldo-editor
